require("plugins")
require("options")
require("keymaps")

require("configs.lsp")
require("configs.lualine")
-- require("configs.harpoon")
-- require("configs.codeium")
require("configs.telescope")
require("configs.which-key")
-- require("configs.nvim-cmp")
require("configs.treesitter")
require("configs.tokyonight")
