require("core.plugins")
require("core.options")
require("core.keymaps")

require("core.configs.lsp")
require("core.configs.lualine")
require("core.configs.harpoon")
-- require("core.configs.codeium")
require("core.configs.neo-tree")
require("core.configs.telescope")
require("core.configs.which-key")
-- require("core.configs.nvim-cmp")
-- require("core.configs.nvim-tree")
require("core.configs.treesitter")
require("core.configs.tokyonight")
